#!/usr/bin/env python3
"""Prepare private owner-review intake for KMFA v0.1.4 candidate draft.

This phase does not read the raw inbox. It consumes the ignored private
candidate draft generated by the prior phase and prepares a grouped private
review package so an owner or authorized delegate can confirm, reject, or keep
pending the candidate source evidence with less free-text work.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from copy import deepcopy
from datetime import datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))


PROJECT_ROOT = Path("KMFA")
PHASE_ID = "V014_PROCESSED_VALUE_SOURCE_MAP_COMPLETION_OWNER_REVIEW_INTAKE_PREP"
TASK_ID = "KMFA-V014-PROCESSED-VALUE-SOURCE-MAP-COMPLETION-OWNER-REVIEW-INTAKE-PREP-20260706"
ACCEPTANCE_ID = "ACC-V014-PROCESSED-VALUE-SOURCE-MAP-COMPLETION-OWNER-REVIEW-INTAKE-PREP"
VERSION = "0.1.4-processed-value-source-map-completion-owner-review-intake-prep"
STATUS = "completed_validated_local_only_no_go_owner_review_intake_ready"
NEXT_REQUIRED_INPUT = "owner_or_authorized_delegate_fills_private_owner_review_response_template"

ARTIFACT_DIR = PROJECT_ROOT / "stage_artifacts" / PHASE_ID
MACHINE_DIR = ARTIFACT_DIR / "machine"
HUMAN_DIR = ARTIFACT_DIR / "human"
SUMMARY_PATH = MACHINE_DIR / "processed_value_source_map_completion_owner_review_intake_prep_summary.json"
MANIFEST_PATH = MACHINE_DIR / "processed_value_source_map_completion_owner_review_intake_prep_manifest.json"
GO_NO_GO_PATH = MACHINE_DIR / "processed_value_source_map_completion_owner_review_intake_prep_go_no_go_report.json"
REPORT_PATH = HUMAN_DIR / "processed_value_source_map_completion_owner_review_intake_prep_report.md"
GO_NO_GO_RECORD_PATH = HUMAN_DIR / "go_no_go_record.md"
TEST_RESULTS_PATH = HUMAN_DIR / "test_results.md"
RISK_REGISTER_PATH = HUMAN_DIR / "risk_register.md"
ROLLBACK_PATH = HUMAN_DIR / "rollback_plan.md"

METADATA_SUMMARY_PATH = PROJECT_ROOT / "metadata/quality/v014_processed_value_source_map_completion_owner_review_intake_prep_summary.json"
METADATA_MANIFEST_PATH = PROJECT_ROOT / "metadata/quality/v014_processed_value_source_map_completion_owner_review_intake_prep_manifest.json"
METADATA_GO_NO_GO_PATH = PROJECT_ROOT / "metadata/quality/v014_processed_value_source_map_completion_owner_review_intake_prep_go_no_go_report.json"
DEVELOPMENT_EVENTS_PATH = PROJECT_ROOT / "docs/governance/development_events.jsonl"

SOURCE_PRIVATE_DIR = PROJECT_ROOT / ".codex_private_runtime/v014_processed_value_source_map_completion_auto_candidate_draft"
SOURCE_CANDIDATE_DRAFT_PATH = SOURCE_PRIVATE_DIR / "auto_candidate_completion_template_draft.json"
SOURCE_MATCH_DIAGNOSTIC_PATH = SOURCE_PRIVATE_DIR / "auto_match_diagnostic.json"
PRIVATE_OUTPUT_DIR = PROJECT_ROOT / ".codex_private_runtime/v014_processed_value_source_map_completion_owner_review_intake_prep"
PRIVATE_GROUPED_REVIEW_PATH = PRIVATE_OUTPUT_DIR / "private_grouped_owner_review_intake.json"
PRIVATE_RESPONSE_TEMPLATE_PATH = PRIVATE_OUTPUT_DIR / "private_owner_review_response_template.json"
PRIVATE_CANDIDATE_CATALOG_PATH = PRIVATE_OUTPUT_DIR / "private_candidate_catalog.json"
PRIVATE_COMPRESSED_QUESTION_LIST_PATH = PRIVATE_OUTPUT_DIR / "private_grouped_question_list_zh.md"

OWNER_DECISION_CODES = [
    "confirm_group_candidate_rank",
    "choose_candidate_record_ref",
    "keep_pending",
    "mark_not_applicable",
    "request_more_diagnostics",
]


def _now(generated_at: str | None = None) -> str:
    return generated_at or datetime.now().astimezone().isoformat(timespec="seconds")


def _read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _git_output(args: list[str]) -> str:
    result = subprocess.run(
        ["git", "-c", "core.quotePath=false", *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        return "UNKNOWN"
    return result.stdout.strip()


def _git_check_ignored(path: Path) -> bool:
    return subprocess.run(["git", "check-ignore", "-q", path.as_posix()], check=False).returncode == 0


def _group_id(index: int, context_group: str, status: str) -> str:
    normalized = "".join(ch if ch.isalnum() else "-" for ch in context_group).strip("-").lower()
    return f"ORG-{index:03d}-{normalized}-{status[:12]}"


def _top_candidate_records(context_candidate: dict[str, Any]) -> list[dict[str, Any]]:
    records = context_candidate.get("top_candidate_records", [])
    if not isinstance(records, list):
        return []
    result: list[dict[str, Any]] = []
    seen: set[str] = set()
    for record in records:
        if not isinstance(record, dict):
            continue
        key = str(record.get("record_ref_hash") or record.get("numeric_value_fingerprint") or len(result))
        if key in seen:
            continue
        seen.add(key)
        enriched = deepcopy(record)
        enriched["candidate_rank"] = len(result) + 1
        result.append(enriched)
        if len(result) >= 20:
            break
    return result


def _build_private_review_package(
    *,
    generated_at: str,
    source_draft: dict[str, Any],
    source_diagnostic: dict[str, Any],
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any], str]:
    items = source_draft.get("candidate_completion_items", [])
    if not isinstance(items, list):
        raise ValueError("candidate_completion_items must be a list")
    context_candidates = source_draft.get("context_candidates", {})
    if not isinstance(context_candidates, dict):
        raise ValueError("context_candidates must be an object")

    by_context: dict[str, list[dict[str, Any]]] = {}
    for item in items:
        if isinstance(item, dict):
            by_context.setdefault(str(item.get("context_group", "")), []).append(item)

    review_groups: list[dict[str, Any]] = []
    response_rows: list[dict[str, Any]] = []
    candidate_catalog_records: list[dict[str, Any]] = []
    for group_index, context_group in enumerate(sorted(by_context), 1):
        group_items = by_context[context_group]
        context_candidate = context_candidates.get(context_group, {})
        if not isinstance(context_candidate, dict):
            context_candidate = {}
        status = str(context_candidate.get("candidate_status", "missing_context_candidate"))
        group_id = _group_id(group_index, context_group, status)
        top_records = _top_candidate_records(context_candidate)
        for record in top_records:
            catalog_record = deepcopy(record)
            catalog_record["review_group_id"] = group_id
            catalog_record["context_group"] = context_group
            candidate_catalog_records.append(catalog_record)
        review_groups.append(
            {
                "review_group_id": group_id,
                "context_group": context_group,
                "candidate_status": status,
                "target_slot_count": len(group_items),
                "target_slot_ids": [item.get("target_slot_id") for item in group_items],
                "candidate_record_count": int(context_candidate.get("candidate_record_count", 0) or 0),
                "candidate_unique_numeric_fingerprint_count": int(
                    context_candidate.get("candidate_unique_numeric_fingerprint_count", 0) or 0
                ),
                "top_candidate_record_count": len(top_records),
                "top_candidate_records": top_records,
                "owner_review_instruction_zh": (
                    "请为该组确认可复用候选排名、指定单条 candidate record ref，或选择 keep_pending / "
                    "mark_not_applicable / request_more_diagnostics。"
                ),
            }
        )
        for item in group_items:
            response_rows.append(
                {
                    "target_slot_id": item.get("target_slot_id"),
                    "context_group": context_group,
                    "review_group_id": group_id,
                    "candidate_status": status,
                    "allowed_owner_decision_codes": OWNER_DECISION_CODES,
                    "owner_decision_code": "PENDING_OWNER_OR_AUTHORIZED_DELEGATE_REVIEW",
                    "selected_candidate_rank": "PENDING_OWNER_OR_AUTHORIZED_DELEGATE_REVIEW",
                    "selected_candidate_record_ref_hash": "PENDING_OWNER_OR_AUTHORIZED_DELEGATE_REVIEW",
                    "selected_processed_value_fingerprint": "PENDING_OWNER_OR_AUTHORIZED_DELEGATE_REVIEW",
                    "owner_or_authorized_delegate_role": "PENDING_OWNER_OR_AUTHORIZED_DELEGATE_REVIEW",
                    "authorization_timestamp": "PENDING_OWNER_OR_AUTHORIZED_DELEGATE_REVIEW",
                    "basis_note": "PENDING_OWNER_OR_AUTHORIZED_DELEGATE_REVIEW",
                    "public_commit_policy": "do_not_commit_this_private_response_template_or_business_values",
                }
            )

    grouped_review = {
        "schema_version": "kmfa.private.v014_processed_value_source_map_completion_owner_review_intake.v1",
        "classification": "private_grouped_owner_review_intake_do_not_commit",
        "record_type": "v014_processed_value_source_map_completion_owner_review_intake",
        "project_id": "KMFA",
        "version": VERSION,
        "phase_id": PHASE_ID,
        "task_id": TASK_ID,
        "generated_at": generated_at,
        "source_candidate_draft_phase_id": source_draft.get("phase_id"),
        "source_candidate_status_counts": source_draft.get("candidate_status_counts", {}),
        "source_unresolved_item_count": source_diagnostic.get("unresolved_item_count"),
        "review_group_count": len(review_groups),
        "response_template_row_count": len(response_rows),
        "owner_decision_codes": OWNER_DECISION_CODES,
        "review_groups": review_groups,
    }
    response_template = {
        "schema_version": "kmfa.private.v014_processed_value_source_map_completion_owner_review_response_template.v1",
        "classification": "private_owner_review_response_template_do_not_commit",
        "record_type": "v014_processed_value_source_map_completion_owner_review_response_template",
        "project_id": "KMFA",
        "version": VERSION,
        "phase_id": PHASE_ID,
        "task_id": TASK_ID,
        "generated_at": generated_at,
        "response_template_is_active_authorization_record": False,
        "completion_template_overwritten": False,
        "active_owner_authorized_fill_record_written": False,
        "owner_decision_codes": OWNER_DECISION_CODES,
        "response_row_count": len(response_rows),
        "response_rows": response_rows,
    }
    candidate_catalog = {
        "schema_version": "kmfa.private.v014_processed_value_source_map_completion_owner_review_candidate_catalog.v1",
        "classification": "private_candidate_catalog_do_not_commit",
        "record_type": "v014_processed_value_source_map_completion_owner_review_candidate_catalog",
        "project_id": "KMFA",
        "version": VERSION,
        "phase_id": PHASE_ID,
        "task_id": TASK_ID,
        "generated_at": generated_at,
        "candidate_catalog_record_count": len(candidate_catalog_records),
        "candidate_catalog_records": candidate_catalog_records,
    }
    lines = [
        "# KMFA v0.1.4 private owner review 分组问题清单",
        "",
        "说明：本文件包含 raw 细节、候选上下文和候选值诊断，只能保留在 `.codex_private_runtime/`，不得提交 GitHub。",
        "",
        f"- 待确认 target slot：{len(response_rows)}",
        f"- 分组问题数：{len(review_groups)}",
        f"- 可选 owner decision codes：{', '.join(OWNER_DECISION_CODES)}",
        "",
    ]
    for group in review_groups:
        lines.extend(
            [
                f"## {group['review_group_id']}",
                "",
                f"- context_group：{group['context_group']}",
                f"- candidate_status：{group['candidate_status']}",
                f"- target_slot_count：{group['target_slot_count']}",
                f"- candidate_record_count：{group['candidate_record_count']}",
                f"- candidate_unique_numeric_fingerprint_count：{group['candidate_unique_numeric_fingerprint_count']}",
                "- 需要确认：该组是否可共用某个候选排名；如果不能共用，请在 response template 逐项指定。",
                "",
            ]
        )
        for record in group["top_candidate_records"][:5]:
            lines.extend(
                [
                    f"- 候选排名 {record.get('candidate_rank')}",
                    f"  - record_ref_hash: {record.get('record_ref_hash')}",
                    f"  - numeric_value_fingerprint: {record.get('numeric_value_fingerprint')}",
                    f"  - raw_file_name: {record.get('raw_file_name')}",
                    f"  - archive_member_name: {record.get('archive_member_name')}",
                    f"  - sheet_name: {record.get('sheet_name')}",
                    f"  - cell_address/page_token: {record.get('cell_address') or (str(record.get('page_index')) + '/' + str(record.get('token_index')) if record.get('page_index') else '')}",
                    f"  - raw_value: {record.get('raw_value')}",
                    f"  - context_text: {record.get('context_text')}",
                ]
            )
        lines.append("")
    return grouped_review, response_template, candidate_catalog, "\n".join(lines)


def _raw_boundary() -> dict[str, bool]:
    return {
        "raw_data_root_readonly_policy_active": True,
        "raw_inbox_read_performed_by_this_phase": False,
        "raw_inbox_list_performed_by_this_phase": False,
        "raw_inbox_stat_performed_by_this_phase": False,
        "raw_inbox_hash_or_value_fingerprint_performed_by_this_phase": False,
        "raw_inbox_write_performed_by_this_phase": False,
        "raw_inbox_delete_performed_by_this_phase": False,
        "raw_inbox_move_performed_by_this_phase": False,
        "raw_inbox_rename_performed_by_this_phase": False,
        "raw_inbox_overwrite_performed_by_this_phase": False,
        "raw_inbox_copy_performed_by_this_phase": False,
        "raw_inbox_normalize_performed_by_this_phase": False,
        "raw_inbox_mutated_by_this_phase": False,
    }


def _public_safety() -> dict[str, bool]:
    return {
        "public_safe_aggregate_only": True,
        "private_grouped_review_committed": False,
        "private_response_template_committed": False,
        "private_candidate_catalog_committed": False,
        "private_question_list_committed": False,
        "raw_file_committed": False,
        "raw_filename_committed": False,
        "raw_archive_member_name_committed": False,
        "field_header_plaintext_committed": False,
        "row_value_committed": False,
        "business_value_committed": False,
        "credential_or_secret_committed": False,
    }


def _write_public_artifacts(
    *,
    generated_at: str,
    grouped_review: dict[str, Any],
    response_template: dict[str, Any],
    candidate_catalog: dict[str, Any],
    source_draft: dict[str, Any],
) -> dict[str, Any]:
    source_counts = source_draft.get("candidate_status_counts", {})
    summary = {
        "schema_version": "kmfa.v014_processed_value_source_map_completion_owner_review_intake_prep_summary.v1",
        "record_type": "v014_processed_value_source_map_completion_owner_review_intake_prep_summary",
        "project_id": "KMFA",
        "version": VERSION,
        "phase_id": PHASE_ID,
        "task_id": TASK_ID,
        "acceptance_id": ACCEPTANCE_ID,
        "status": STATUS,
        "generated_at": generated_at,
        "source_candidate_draft_phase_id": source_draft.get("phase_id"),
        "source_candidate_draft_item_count": source_draft.get("candidate_draft_item_count"),
        "source_auto_ambiguous_candidate_item_count": source_counts.get(
            "auto_ambiguous_multiple_candidates_requires_owner_review", 0
        ),
        "source_auto_unmatched_item_count": source_counts.get("auto_unmatched_requires_owner_review", 0),
        "source_non_numeric_or_calculation_context_item_count": source_counts.get("requires_non_numeric_owner_mapping", 0),
        "review_group_count": grouped_review["review_group_count"],
        "response_template_row_count": response_template["response_row_count"],
        "candidate_catalog_record_count": candidate_catalog["candidate_catalog_record_count"],
        "private_grouped_review_written": True,
        "private_response_template_written": True,
        "private_candidate_catalog_written": True,
        "private_grouped_question_list_written": True,
        "private_grouped_review_gitignored": _git_check_ignored(PRIVATE_GROUPED_REVIEW_PATH),
        "private_response_template_gitignored": _git_check_ignored(PRIVATE_RESPONSE_TEMPLATE_PATH),
        "private_candidate_catalog_gitignored": _git_check_ignored(PRIVATE_CANDIDATE_CATALOG_PATH),
        "private_grouped_question_list_gitignored": _git_check_ignored(PRIVATE_COMPRESSED_QUESTION_LIST_PATH),
        "response_template_is_active_authorization_record": False,
        "completion_template_overwritten": False,
        "active_owner_authorized_fill_record_written": False,
        "authorized_completion_record_supplied": False,
        "source_map_completion_reapplication_ready": False,
        "source_map_completion_reapplication_performed": False,
        "source_map_records_applied_count": 0,
        "processed_value_materialization_replay_performed": False,
        "raw_to_processed_value_comparison_performed": False,
        "business_value_consistency_verified": False,
        "lineage_full_check_complete": False,
        "formal_report_allowed": False,
        "github_upload_performed": False,
        "app_reinstall_performed": False,
        "business_execution_performed": False,
        "decision": "NO_GO",
        "diagnostic_conclusion": "private_owner_review_intake_ready_owner_response_required",
        "next_required_input": NEXT_REQUIRED_INPUT,
        "raw_boundary": _raw_boundary(),
        "public_safety": _public_safety(),
    }
    go_no_go = {
        "schema_version": "kmfa.v014_processed_value_source_map_completion_owner_review_intake_prep_go_no_go.v1",
        "record_type": "v014_processed_value_source_map_completion_owner_review_intake_prep_go_no_go_report",
        "project_id": "KMFA",
        "version": VERSION,
        "phase_id": PHASE_ID,
        "task_id": TASK_ID,
        "acceptance_id": ACCEPTANCE_ID,
        "generated_at": generated_at,
        "decision": "NO_GO",
        "status": STATUS,
        "diagnostic_conclusion": "private_owner_review_intake_ready_owner_response_required",
        "review_group_count": summary["review_group_count"],
        "response_template_row_count": summary["response_template_row_count"],
        "source_map_completion_reapplication_ready": False,
        "raw_to_processed_value_comparison_performed": False,
        "business_value_consistency_verified": False,
        "github_upload_performed": False,
        "app_reinstall_performed": False,
        "business_execution_performed": False,
        "blocked_until": NEXT_REQUIRED_INPUT,
    }
    manifest = {
        "schema_version": "kmfa.v014_processed_value_source_map_completion_owner_review_intake_prep_manifest.v1",
        "record_type": "v014_processed_value_source_map_completion_owner_review_intake_prep_manifest",
        "project_id": "KMFA",
        "version": VERSION,
        "phase_id": PHASE_ID,
        "task_id": TASK_ID,
        "acceptance_ids": [ACCEPTANCE_ID],
        "generated_at": generated_at,
        "status": STATUS,
        "summary": summary,
        "go_no_go": go_no_go,
        "artifact_refs": {
            "machine_summary": SUMMARY_PATH.as_posix(),
            "machine_manifest": MANIFEST_PATH.as_posix(),
            "machine_go_no_go": GO_NO_GO_PATH.as_posix(),
            "private_grouped_review": "private_runtime_only",
            "private_response_template": "private_runtime_only",
            "private_candidate_catalog": "private_runtime_only",
            "private_grouped_question_list": "private_runtime_only",
        },
        "validator": (
            "PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=. "
            "python3 KMFA/tools/check_v014_processed_value_source_map_completion_owner_review_intake_prep.py "
            "--require-private-intake"
        ),
        "git": {
            "branch": _git_output(["branch", "--show-current"]),
            "head": _git_output(["rev-parse", "HEAD"]),
            "status_short": _git_output(["status", "--short", "--branch"]),
        },
    }
    report = f"""# V014 Processed Value Source-map Completion Owner Review Intake Prep

Decision: NO_GO

This phase prepared a private owner-review intake package from the prior private candidate draft. It did not read the raw inbox, did not write an active authorization record, and did not apply source-map changes.

## Public-safe aggregate result

- Review group count: {summary["review_group_count"]}
- Response template row count: {summary["response_template_row_count"]}
- Private candidate catalog record count: {summary["candidate_catalog_record_count"]}
- Source ambiguous item count: {summary["source_auto_ambiguous_candidate_item_count"]}
- Source unmatched item count: {summary["source_auto_unmatched_item_count"]}
- Source non-numeric/calculation-context item count: {summary["source_non_numeric_or_calculation_context_item_count"]}

Next required input: `{NEXT_REQUIRED_INPUT}`.
"""
    go_no_go_record = f"""# Go/No-Go Record

- phase_id: `{PHASE_ID}`
- decision: `NO_GO`
- reason: private owner-review intake is ready, but owner/authorized-delegate response has not been supplied.
- source-map reapplication ready: `false`
- github upload performed: `false`
"""
    risk_register = """# Risk Register

- Risk: owner response may confirm a candidate at group level when some target slots need separate handling.
  Mitigation: the private response template supports per-target overrides and keeps all rows pending by default.
- Risk: raw detail leakage.
  Mitigation: raw-detail review files are private runtime only; public artifacts contain aggregate counts and gate flags.
"""
    rollback_plan = """# Rollback Plan

No raw file or active authorization record was modified. To roll back, remove this phase's public artifacts and metadata copies, and optionally remove the ignored private intake-prep directory.
"""
    test_results = f"""# Test Results

Pending until validator and focused tests are run after artifact generation.

Expected validator:
`PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=. python3 KMFA/tools/check_v014_processed_value_source_map_completion_owner_review_intake_prep.py --require-private-intake`
"""
    for path, payload in (
        (SUMMARY_PATH, summary),
        (MANIFEST_PATH, manifest),
        (GO_NO_GO_PATH, go_no_go),
        (METADATA_SUMMARY_PATH, summary),
        (METADATA_MANIFEST_PATH, manifest),
        (METADATA_GO_NO_GO_PATH, go_no_go),
    ):
        _write_json(path, payload)
    for path, text in (
        (REPORT_PATH, report),
        (GO_NO_GO_RECORD_PATH, go_no_go_record),
        (RISK_REGISTER_PATH, risk_register),
        (ROLLBACK_PATH, rollback_plan),
        (TEST_RESULTS_PATH, test_results),
    ):
        _write_text(path, text)
    return manifest


def _append_development_event(generated_at: str, manifest: dict[str, Any]) -> None:
    event_id = "DEV-KMFA-20260706-V014-PROCESSED-VALUE-SOURCE-MAP-COMPLETION-OWNER-REVIEW-INTAKE-PREP"
    event = {
        "event_id": event_id,
        "event_time": generated_at,
        "event_type": "development",
        "project_id": "KMFA",
        "phase_id": PHASE_ID,
        "task_id": TASK_ID,
        "version": VERSION,
        "iteration_id": "ITER-20260706-KMFA-V014-PROCESSED-VALUE-SOURCE-MAP-COMPLETION-OWNER-REVIEW-INTAKE-PREP",
        "fact_level": "EXTRACTED",
        "evidence_ref": MANIFEST_PATH.as_posix(),
        "go_no_go": manifest["go_no_go"]["decision"],
        "review_group_count": manifest["summary"]["review_group_count"],
        "response_template_row_count": manifest["summary"]["response_template_row_count"],
        "raw_inbox_read_performed": False,
        "raw_inbox_mutation_performed": False,
        "raw_to_processed_value_comparison_performed": False,
        "business_value_consistency_verified": False,
        "github_upload_performed": False,
        "app_reinstall_performed": False,
        "business_execution_performed": False,
        "result_commit": "PENDING",
        "summary": (
            "Prepared a private grouped owner-review intake package and response template from the prior candidate "
            "draft. Public evidence is aggregate-only and downstream application remains blocked until owner or "
            "authorized-delegate response is supplied."
        ),
    }
    DEVELOPMENT_EVENTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    existing = DEVELOPMENT_EVENTS_PATH.read_text(encoding="utf-8").splitlines() if DEVELOPMENT_EVENTS_PATH.exists() else []
    filtered = [line for line in existing if f'"event_id":"{event_id}"' not in line and f'"event_id": "{event_id}"' not in line]
    filtered.append(json.dumps(event, ensure_ascii=False, sort_keys=True))
    DEVELOPMENT_EVENTS_PATH.write_text("\n".join(filtered) + "\n", encoding="utf-8")


def generate(*, generated_at: str | None = None, write_governance_event: bool = True) -> dict[str, Any]:
    timestamp = _now(generated_at)
    source_draft = _read_json(SOURCE_CANDIDATE_DRAFT_PATH)
    source_diagnostic = _read_json(SOURCE_MATCH_DIAGNOSTIC_PATH)
    grouped_review, response_template, candidate_catalog, question_list = _build_private_review_package(
        generated_at=timestamp,
        source_draft=source_draft,
        source_diagnostic=source_diagnostic,
    )
    _write_json(PRIVATE_GROUPED_REVIEW_PATH, grouped_review)
    _write_json(PRIVATE_RESPONSE_TEMPLATE_PATH, response_template)
    _write_json(PRIVATE_CANDIDATE_CATALOG_PATH, candidate_catalog)
    _write_text(PRIVATE_COMPRESSED_QUESTION_LIST_PATH, question_list)
    manifest = _write_public_artifacts(
        generated_at=timestamp,
        grouped_review=grouped_review,
        response_template=response_template,
        candidate_catalog=candidate_catalog,
        source_draft=source_draft,
    )
    if write_governance_event:
        _append_development_event(timestamp, manifest)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--generated-at")
    args = parser.parse_args()
    manifest = generate(generated_at=args.generated_at)
    print(
        "PASS: KMFA v0.1.4 owner review intake prep generated "
        f"(decision={manifest['go_no_go']['decision']}, "
        f"review_groups={manifest['summary']['review_group_count']}, "
        f"response_rows={manifest['summary']['response_template_row_count']})"
    )


if __name__ == "__main__":
    main()
