const CUE = {
  "_": "全片唯一时间表（秒）。画面 src/*.js 与配乐 music.py 都读这份文件：改一个时间，画面和声音一起动。120 BPM，1 拍 = 0.5s，1 小节 = 2s。本文件须保持严格 JSON（music.py 直接解析）。",
  "bpm": 120,
  "dur": 46.0,
  "sections": [
    { "name": "intro",     "t0": 0,  "t1": 4,  "key": "F",  "note": "拨弦 vamp + 嘎吱声，窑宝咯噔" },
    { "name": "verse",     "t0": 4,  "t1": 8,  "key": "F",  "note": "鼓进场，厂长吃热干面，三次咯噔" },
    { "name": "nightmare", "t0": 8,  "t1": 12, "key": "Dm", "note": "小调大号，思想气泡：拆窑、压扁卡车、停产 60 天" },
    { "name": "build",     "t0": 12, "t1": 16, "key": "F",  "note": "落体哨音，箱子砸地，军鼓加速，15.75 留白" },
    { "name": "chorus1",   "t0": 16, "t1": 28, "key": "F",  "note": "Drop：测跳动 → 在线车削 → 托轮 → 齿圈" },
    { "name": "break",     "t0": 28, "t1": 32, "key": "F",  "note": "唱片急停，只剩秒针；跳动归零，窑宝打嗝，击掌" },
    { "name": "chorus2",   "t0": 32, "t1": 40, "key": "F",  "note": "升上云端：五个行业岛，近万家企业" },
    { "name": "outro",     "t0": 40, "t1": 46, "key": "F",  "note": "回到窑宝；片尾卡；最后一个咯噔是 Clawd 在跳" }
  ],
  "ev": {
    "irisOpen": 0.0,
    "clunk1": 1.0, "clunk2": 2.0, "clunk3": 3.0,
    "drumsIn": 4.0,
    "nclunk1": 5.0, "nclunk2": 6.0, "nclunk3": 7.0, "noodleHat": 7.45,
    "bubble": 8.0, "intoBubble": 8.5, "craneLift": 9.0, "squash": 10.0, "calendar": 10.4, "coins": 11.0, "bubblePop": 11.6,
    "fallStart": 12.0, "crateLand": 13.0, "rollStart": 13.5, "peek": 15.0, "gap": 15.75, "drop": 16.0,
    "hopOn": 16.4, "hopLand": 16.9, "gaugeOn": 18.0, "idea": 19.0,
    "toolIn": 20.0, "cutStart": 20.5, "chipSnap": 22.0, "chipLand": 22.8, "mirror": 23.1, "shades": 23.5,
    "roller": 24.0, "whipGear": 26.0, "weld": 26.3, "chomp": 27.3,
    "scratch": 28.0, "zero": 29.0, "listen": 29.6, "burp": 30.5, "hi5": 31.8,
    "rise": 32.0, "isle1": 33.5, "isle2": 34.5, "isle3": 35.5, "isle4": 36.5, "isle5": 37.5, "count": 38.0, "tada": 39.5,
    "dive": 40.0, "card": 41.0, "card2": 42.0, "card3": 43.0, "lastClunk": 44.0, "wink": 45.0, "button": 45.5, "irisClose": 45.2
  },
  "captions": [
    { "t0": 0.6,  "t1": 3.9,  "zh": "窑宝又{咯噔}了……",               "en": "The kiln is clunking again…" },
    { "t0": 4.15, "t1": 7.9,  "zh": "它{咯噔}一下，厂长心里也{咯噔}一下", "en": "Every clunk — the boss's heart clunks too." },
    { "t0": 8.2,  "t1": 11.9, "zh": "拆下来运走修？{停产两个月}？！",    "en": "Ship it out? Two months of downtime?!" },
    { "t0": 12.2, "t1": 15.7, "zh": "等等……天上掉下来个啥？",            "en": "Wait… what just fell from the sky?" },
    { "t0": 16.3, "t1": 19.9, "zh": "{不停窑}！先测跳动",                "en": "No shutdown. Measure the runout first." },
    { "t0": 20.2, "t1": 23.9, "zh": "窑照转，{现场车削}，车成镜面",      "en": "Kiln keeps turning. Machined live, to a mirror finish." },
    { "t0": 24.2, "t1": 25.9, "zh": "{托轮}磨损？修！",                  "en": "Worn support roller? Fixed." },
    { "t0": 26.2, "t1": 27.9, "zh": "{断齿}？现场焊一颗新的！",          "en": "Broken tooth? We grow a new one, on site." },
    { "t0": 28.5, "t1": 31.9, "zh": "跳动{归零}。窑宝：嗝~ 舒服了",      "en": "Runout: zero. Kiln: *burp* …much better." },
    { "t0": 33.0, "t1": 39.9, "zh": "全国{近万家企业}的设备保姆",        "en": "Equipment nanny to nearly 10,000 plants." },
    { "t0": 41.0, "t1": 45.3, "zh": "设备坏了别慌，{找开明}！",          "en": "Machine acting up? Call Kaiming!" }
  ],
  "sfx": [
    { "t": 0.0,  "k": "shimmer" },
    { "t": 1.0,  "k": "clunk" }, { "t": 2.0, "k": "clunk" }, { "t": 3.0, "k": "clunk" },
    { "t": 0.5,  "k": "creak" }, { "t": 1.5, "k": "creak" }, { "t": 2.5, "k": "creak" }, { "t": 3.5, "k": "creak" },
    { "t": 5.0,  "k": "clunk" }, { "t": 6.0, "k": "clunk" }, { "t": 7.0, "k": "clunkBig" },
    { "t": 5.05, "k": "boing", "p": 1.0 }, { "t": 6.05, "k": "boing", "p": 1.2 }, { "t": 7.05, "k": "slideUp" },
    { "t": 7.45, "k": "splat" },
    { "t": 8.0,  "k": "pop" }, { "t": 8.5, "k": "whooshIn" },
    { "t": 9.0,  "k": "crane" }, { "t": 10.0, "k": "squash" },
    { "t": 10.4, "k": "riffle" }, { "t": 11.0, "k": "coins" }, { "t": 11.5, "k": "sadTrombone" }, { "t": 11.6, "k": "pop" },
    { "t": 12.0, "k": "fallWhistle" }, { "t": 13.0, "k": "impact" }, { "t": 13.5, "k": "rattle" },
    { "t": 15.0, "k": "peek" },
    { "t": 16.0, "k": "burst" }, { "t": 16.4, "k": "jump" }, { "t": 16.9, "k": "landBoing" },
    { "t": 17.0, "k": "patter" },
    { "t": 18.0, "k": "clickMag" }, { "t": 18.1, "k": "wobble" }, { "t": 19.0, "k": "ding" },
    { "t": 20.0, "k": "rollIn" },
    { "t": 20.5, "k": "cut" }, { "t": 21.0, "k": "cut" }, { "t": 21.5, "k": "cut" }, { "t": 22.0, "k": "sproing" },
    { "t": 22.8, "k": "ding" }, { "t": 23.1, "k": "gleam" }, { "t": 23.5, "k": "shades" },
    { "t": 24.0, "k": "whooshDown" }, { "t": 24.2, "k": "grind" },
    { "t": 26.0, "k": "whip" }, { "t": 26.3, "k": "weld" }, { "t": 27.3, "k": "chomp" }, { "t": 27.35, "k": "boingUp" },
    { "t": 28.0, "k": "scratch" },
    { "t": 28.5, "k": "tick" }, { "t": 29.0, "k": "ting" }, { "t": 29.5, "k": "tick" }, { "t": 30.0, "k": "tick" },
    { "t": 30.5, "k": "burp" }, { "t": 31.0, "k": "aww" }, { "t": 31.8, "k": "slap" },
    { "t": 32.0, "k": "whooshUp" },
    { "t": 33.5, "k": "popHi", "p": 1.0 }, { "t": 34.5, "k": "popHi", "p": 1.12 }, { "t": 35.5, "k": "popHi", "p": 1.26 },
    { "t": 36.5, "k": "popHi", "p": 1.33 }, { "t": 37.5, "k": "popHi", "p": 1.5 },
    { "t": 38.0, "k": "counter" }, { "t": 39.5, "k": "tada" },
    { "t": 40.0, "k": "whooshDown" }, { "t": 41.0, "k": "slam" }, { "t": 42.0, "k": "popHi", "p": 1.0 }, { "t": 43.0, "k": "popHi", "p": 1.26 },
    { "t": 44.0, "k": "clunk" }, { "t": 44.05, "k": "boing", "p": 1.3 },
    { "t": 45.0, "k": "wink" }, { "t": 45.5, "k": "button" }
  ]
};
if (typeof module !== 'undefined') module.exports = CUE;
