CREATE TABLE IF NOT EXISTS workspaces (
  workspace_id TEXT PRIMARY KEY,
  recovery_hash TEXT NOT NULL UNIQUE,
  project_name TEXT NOT NULL,
  progress INTEGER NOT NULL CHECK(progress BETWEEN 0 AND 100),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS access_tokens (
  token_hash TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id),
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS access_tokens_workspace
  ON access_tokens(workspace_id);

CREATE TABLE IF NOT EXISTS artifacts (
  artifact_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL UNIQUE REFERENCES workspaces(workspace_id),
  object_name TEXT NOT NULL UNIQUE,
  original_name TEXT NOT NULL,
  reported_media_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL CHECK(size_bytes >= 0),
  sha256 TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_events (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id),
  action TEXT NOT NULL,
  result_status TEXT NOT NULL,
  artifact_sha256 TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS walking_audit_workspace
  ON audit_events(workspace_id);

CREATE OR REPLACE FUNCTION kmfa_reject_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'walking-skeleton audit is append-only';
END;
$$;

DROP TRIGGER IF EXISTS walking_audit_no_update ON audit_events;
CREATE TRIGGER walking_audit_no_update
BEFORE UPDATE ON audit_events
FOR EACH ROW EXECUTE FUNCTION kmfa_reject_audit_mutation();

DROP TRIGGER IF EXISTS walking_audit_no_delete ON audit_events;
CREATE TRIGGER walking_audit_no_delete
BEFORE DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION kmfa_reject_audit_mutation();
