CREATE TABLE IF NOT EXISTS consistency_operations (
  operation_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id),
  operation_kind TEXT NOT NULL
    CHECK(operation_kind IN ('upload', 'process', 'index', 'export')),
  idempotency_key_hash TEXT NOT NULL
    CHECK(idempotency_key_hash ~ '^[0-9a-f]{64}$'),
  request_fingerprint TEXT NOT NULL
    CHECK(request_fingerprint ~ '^[0-9a-f]{64}$'),
  artifact_id TEXT,
  artifact_version_id TEXT,
  storage_backend TEXT,
  storage_key TEXT,
  staged_object_name TEXT
    CHECK(staged_object_name IS NULL
      OR (
        char_length(staged_object_name) BETWEEN 1 AND 180
        AND position('/' IN staged_object_name) = 0
        AND position(E'\\' IN staged_object_name) = 0
      )),
  original_name TEXT,
  reported_media_type TEXT,
  size_bytes BIGINT CHECK(size_bytes IS NULL OR size_bytes >= 0),
  content_sha256 TEXT
    CHECK(content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
  state TEXT NOT NULL
    CHECK(state IN (
      'intent_recorded',
      'effect_pending',
      'effect_applied',
      'commit_pending',
      'outbox_committed',
      'converged',
      'isolated'
    )),
  attempt_count BIGINT NOT NULL DEFAULT 0 CHECK(attempt_count >= 0),
  next_attempt_at TEXT,
  last_error_code TEXT,
  row_version BIGINT NOT NULL DEFAULT 1 CHECK(row_version >= 1),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(workspace_id, operation_kind, idempotency_key_hash),
  CHECK(
    operation_kind != 'upload'
    OR (
      artifact_id IS NOT NULL
      AND artifact_version_id IS NOT NULL
      AND storage_backend IS NOT NULL
      AND storage_key IS NOT NULL
      AND staged_object_name IS NOT NULL
      AND original_name IS NOT NULL
      AND reported_media_type IS NOT NULL
      AND size_bytes IS NOT NULL
      AND content_sha256 IS NOT NULL
    )
  )
);

CREATE INDEX IF NOT EXISTS consistency_operations_reconcile
  ON consistency_operations(state, next_attempt_at, updated_at, operation_id);

CREATE TABLE IF NOT EXISTS consistency_outbox (
  outbox_event_id TEXT PRIMARY KEY,
  operation_id TEXT NOT NULL REFERENCES consistency_operations(operation_id),
  effect_kind TEXT NOT NULL
    CHECK(effect_kind IN ('upload', 'process', 'index', 'export', 'notify')),
  dedupe_key TEXT NOT NULL UNIQUE
    CHECK(dedupe_key ~ '^[0-9a-f]{64}$'),
  state TEXT NOT NULL
    CHECK(state IN ('pending', 'leased', 'retry', 'delivered', 'isolated')),
  attempt_count BIGINT NOT NULL DEFAULT 0 CHECK(attempt_count >= 0),
  available_at TEXT NOT NULL,
  lease_until TEXT,
  last_error_code TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(operation_id, effect_kind)
);

CREATE INDEX IF NOT EXISTS consistency_outbox_delivery
  ON consistency_outbox(state, available_at, lease_until, outbox_event_id);

CREATE TABLE IF NOT EXISTS consistency_effect_receipts (
  dedupe_key TEXT PRIMARY KEY
    REFERENCES consistency_outbox(dedupe_key),
  operation_id TEXT NOT NULL REFERENCES consistency_operations(operation_id),
  effect_kind TEXT NOT NULL
    CHECK(effect_kind IN ('upload', 'process', 'index', 'export', 'notify')),
  receipt_hash TEXT NOT NULL
    CHECK(receipt_hash ~ '^[0-9a-f]{64}$'),
  applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS consistency_trace (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trace_event_id TEXT NOT NULL UNIQUE,
  operation_id TEXT NOT NULL REFERENCES consistency_operations(operation_id),
  from_state TEXT,
  to_state TEXT NOT NULL,
  transition_code TEXT NOT NULL,
  error_code TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS consistency_trace_operation
  ON consistency_trace(operation_id, seq);

CREATE OR REPLACE FUNCTION kmfa_reject_consistency_trace_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'consistency trace is append-only';
END;
$$;

DROP TRIGGER IF EXISTS consistency_trace_no_update ON consistency_trace;
CREATE TRIGGER consistency_trace_no_update
BEFORE UPDATE ON consistency_trace
FOR EACH ROW EXECUTE FUNCTION kmfa_reject_consistency_trace_mutation();

DROP TRIGGER IF EXISTS consistency_trace_no_delete ON consistency_trace;
CREATE TRIGGER consistency_trace_no_delete
BEFORE DELETE ON consistency_trace
FOR EACH ROW EXECUTE FUNCTION kmfa_reject_consistency_trace_mutation();

CREATE TABLE IF NOT EXISTS object_quarantine (
  quarantine_id TEXT PRIMARY KEY,
  operation_id TEXT REFERENCES consistency_operations(operation_id),
  storage_backend TEXT NOT NULL,
  storage_key TEXT NOT NULL,
  object_ref TEXT NOT NULL CHECK(object_ref ~ '^[0-9a-f]{20}$'),
  reason_code TEXT NOT NULL,
  state TEXT NOT NULL CHECK(state IN ('isolated', 'released')),
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  UNIQUE(storage_backend, storage_key, reason_code)
);

CREATE INDEX IF NOT EXISTS object_quarantine_state
  ON object_quarantine(state, last_seen_at, quarantine_id);
