CREATE TABLE IF NOT EXISTS restore_drill_proofs (
  proof_id TEXT PRIMARY KEY,
  backup_id TEXT NOT NULL,
  backup_manifest_sha256 TEXT NOT NULL
    CHECK(backup_manifest_sha256 ~ '^[0-9a-f]{64}$'),
  source_schema_version INTEGER NOT NULL CHECK(source_schema_version >= 1),
  expected_fixture_count INTEGER NOT NULL CHECK(expected_fixture_count > 0),
  restored_fixture_count INTEGER NOT NULL CHECK(restored_fixture_count >= 0),
  invariant_failures INTEGER NOT NULL CHECK(invariant_failures >= 0),
  measured_rpo_ms BIGINT NOT NULL CHECK(measured_rpo_ms >= 0),
  measured_rto_ms BIGINT NOT NULL CHECK(measured_rto_ms >= 0),
  artifact_identity_hash TEXT NOT NULL
    CHECK(artifact_identity_hash ~ '^[0-9a-f]{64}$'),
  status TEXT NOT NULL CHECK(status IN ('passed', 'failed')),
  verified_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS restore_drill_proofs_verified
  ON restore_drill_proofs(status, source_schema_version, verified_at, proof_id);

CREATE TABLE IF NOT EXISTS workspace_retention (
  workspace_id TEXT PRIMARY KEY REFERENCES workspaces(workspace_id),
  state TEXT NOT NULL DEFAULT 'active'
    CHECK(state IN (
      'active',
      'deletion_requested',
      'blocked_hold',
      'purge_pending',
      'deleted'
    )),
  active_deletion_request_id TEXT UNIQUE,
  row_version BIGINT NOT NULL DEFAULT 1 CHECK(row_version >= 1),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT
);

INSERT INTO workspace_retention(
  workspace_id, state, active_deletion_request_id, row_version,
  created_at, updated_at, deleted_at
)
SELECT workspace_id, 'active', NULL, 1, created_at, updated_at, NULL
FROM workspaces
ON CONFLICT(workspace_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS legal_holds (
  hold_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id),
  reason_code TEXT NOT NULL
    CHECK(reason_code IN ('legal', 'security', 'regulatory')),
  authority_ref_hash TEXT NOT NULL
    CHECK(authority_ref_hash ~ '^[0-9a-f]{64}$'),
  state TEXT NOT NULL CHECK(state IN ('active', 'released')),
  imposed_at TEXT NOT NULL,
  released_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS legal_holds_one_active_reason
  ON legal_holds(workspace_id, reason_code)
  WHERE state = 'active';

CREATE TABLE IF NOT EXISTS deletion_requests (
  deletion_request_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id),
  idempotency_key_hash TEXT NOT NULL
    CHECK(idempotency_key_hash ~ '^[0-9a-f]{64}$'),
  request_fingerprint TEXT NOT NULL
    CHECK(request_fingerprint ~ '^[0-9a-f]{64}$'),
  restore_proof_id TEXT NOT NULL REFERENCES restore_drill_proofs(proof_id),
  state TEXT NOT NULL
    CHECK(state IN (
      'requested',
      'revoking',
      'purge_pending',
      'retry',
      'blocked_hold',
      'completed'
    )),
  public_purge_due_at TEXT NOT NULL,
  public_purged_at TEXT,
  attempt_count BIGINT NOT NULL DEFAULT 0 CHECK(attempt_count >= 0),
  last_error_code TEXT,
  row_version BIGINT NOT NULL DEFAULT 1 CHECK(row_version >= 1),
  requested_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  completed_at TEXT,
  UNIQUE(workspace_id, idempotency_key_hash)
);

CREATE INDEX IF NOT EXISTS deletion_requests_worker
  ON deletion_requests(state, updated_at, deletion_request_id);

CREATE TABLE IF NOT EXISTS deletion_object_targets (
  deletion_request_id TEXT NOT NULL
    REFERENCES deletion_requests(deletion_request_id),
  artifact_version_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  storage_backend TEXT NOT NULL,
  storage_key TEXT NOT NULL,
  size_bytes BIGINT NOT NULL CHECK(size_bytes >= 0),
  sha256 TEXT NOT NULL CHECK(sha256 ~ '^[0-9a-f]{64}$'),
  state TEXT NOT NULL CHECK(state IN ('pending', 'deleting', 'deleted')),
  attempt_count BIGINT NOT NULL DEFAULT 0 CHECK(attempt_count >= 0),
  last_error_code TEXT,
  deleted_at TEXT,
  PRIMARY KEY(deletion_request_id, artifact_version_id)
);

CREATE INDEX IF NOT EXISTS deletion_object_targets_worker
  ON deletion_object_targets(state, deletion_request_id, artifact_version_id);

CREATE TABLE IF NOT EXISTS publication_bindings (
  publication_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id),
  subject_ref TEXT NOT NULL CHECK(subject_ref ~ '^[0-9a-f]{20}$'),
  state TEXT NOT NULL CHECK(state IN ('active', 'revoked')),
  cache_state TEXT NOT NULL CHECK(cache_state IN ('active', 'purged')),
  index_state TEXT NOT NULL CHECK(index_state IN ('active', 'purged')),
  published_at TEXT NOT NULL,
  revoked_at TEXT,
  purged_at TEXT
);

CREATE INDEX IF NOT EXISTS publication_bindings_workspace_state
  ON publication_bindings(workspace_id, state, publication_id);

CREATE TABLE IF NOT EXISTS lifecycle_events (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE,
  workspace_ref TEXT NOT NULL CHECK(workspace_ref ~ '^[0-9a-f]{20}$'),
  deletion_request_id TEXT REFERENCES deletion_requests(deletion_request_id),
  action TEXT NOT NULL,
  result_status TEXT NOT NULL,
  object_ref TEXT CHECK(object_ref IS NULL OR object_ref ~ '^[0-9a-f]{20}$'),
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS lifecycle_events_request
  ON lifecycle_events(deletion_request_id, seq);

CREATE OR REPLACE FUNCTION kmfa_reject_lifecycle_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'lifecycle events are append-only';
END;
$$;

DROP TRIGGER IF EXISTS lifecycle_events_no_update ON lifecycle_events;
CREATE TRIGGER lifecycle_events_no_update
BEFORE UPDATE ON lifecycle_events
FOR EACH ROW EXECUTE FUNCTION kmfa_reject_lifecycle_event_mutation();

DROP TRIGGER IF EXISTS lifecycle_events_no_delete ON lifecycle_events;
CREATE TRIGGER lifecycle_events_no_delete
BEFORE DELETE ON lifecycle_events
FOR EACH ROW EXECUTE FUNCTION kmfa_reject_lifecycle_event_mutation();
